### ISSUE TITLE
hexo常用指令

### ISSUE THREAD

**Issue by RammusXu** [RammusXu/rammusxu.github.io#13]
發佈到github上

``` bash
 hexo deploy -g
```

_config.yml

``` yml
deploy:
  type: git
  repo: git@github.com:RammusXu/rammusxu.github.io.git
  branch: master
  message: 更改linux預設時區
```

**Comment by RammusXu** [comment]
個人習慣用法

``` md
## Reference
```

``` md
## Issue
### Solution
### Error
### Conclusion
## Notice
```

``` bash
git add .; git commit -m "brew - 加強terminal功能";git push ; hexo deploy -g
```

**Comment by RammusXu** [comment]
```bash
git add .; git commit -m "brew - 加強terminal功能";git push ; hexo deploy -g
```

**Comment by RammusXu** [comment]
### Copy to folder

<img width="469" alt="copy-to-folder" src="https://cloud.githubusercontent.com/assets/4367069/17803510/67ee1266-6629-11e6-976a-77549585ca77.png">

### Usage

``` markdown
![build-jar](build-jar.png)
```

**Comment by RammusXu** [comment]
## 在文章中加入別篇post的方法

``` ejs
{% postlink [another post name] %}
```

### 範例

``` ejs
{% post_link using-gradle-to-create-a-runnable-jar-with-dependencies-in-intellij-idea %}
```

## 在文章中加入圖片的方法

正确的引用图片方式是使用下列的标签插件而不是 markdown

``` ejs
{% asset_img example.jpg This is an example image %}
```

## Reference
- Hexo使用内链及文章中加入图片的方法 http://marshal.ohtly.com/2015/09/12/internal-link-and-image-for-hexo/
- 资源文件夹 https://hexo.io/zh-cn/docs/asset-folders.html

**Comment by RammusXu** [comment]
文章中的標題、日期寫法

``` yml
---
title: 中華台哥中華雙np心得及攻略SOP
date: 2016-08-24 03:30:27
tags: [emome,np]
---
```
