### ISSUE TITLE
如何在mac的terminal中執行上一頁的動作

### ISSUE THREAD

**Issue by RammusXu** [RammusXu/rammusxu.github.io#29]
`fn` + `up` or `fn` + `down` 
如果在編輯器中，像是vim，則要按住`shift` 
## Reference
- How to do Page-Up on a Mac in Terminal http://superuser.com/questions/104221/how-to-do-page-up-on-a-mac-in-terminal

**Comment by RammusXu** [comment]
``` yaml
---
title: 如何在mac的terminal中執行上一頁的動作
date: 2016-08-17 08:05:59
tags: [mac,terminal]
---
```

``` bash
hexo new post how-to-do-page-up-on-a-mac-in-terminal
```

``` bash
git add .; git commit -m "如何在mac的terminal中執行上一頁的動作";git push ; hexo deploy -g
```
