### ISSUE TITLE
Docker - 用Windows架設Wordpress的坑

### ISSUE THREAD

**Issue by RammusXu** [RammusXu/rammusxu.github.io#52]
- pppoe
- wordpress 需要設定 domain
  ![setting_url](https://cloud.githubusercontent.com/assets/4367069/19567089/2880db14-971f-11e6-8555-a0748b1b8139.PNG)
- docker-compose.yml

``` yml
 version: '2'

 services:
   db:
     image: mysql:5.7
     volumes:
       - "./.data/db:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - "./web:/var/www/html"
     links:
       - db
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
```
- docker command

``` bash
docker-compose up
docker-compose up -d
docker-compose down
```
- windows 防火牆輸入規則
<img width="396" alt="2017-03-03 2 25 11" src="https://cloud.githubusercontent.com/assets/4367069/23521123/b45033c2-ffb8-11e6-99a9-6953a58e6612.png">
<img width="402" alt="2017-03-03 2 25 17" src="https://cloud.githubusercontent.com/assets/4367069/23521124/b4503142-ffb8-11e6-9eb2-e0dee20fbe6d.png">

- 上傳檔案限制2M
  - https://github.com/docker-library/wordpress/issues/10

```
create uploads.ini then, content is

file_uploads = On
memory_limit = 64M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 600
use fig.yml solution, to replace uploads.ini

db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: "PASSWORD-HERE"

wordpress:
  image: wordpress:latest
  ports:
    - "80:80"
  links:
    - db:mysql
  volumes:
    - uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
```
## Reference
- https://docs.docker.com/compose/wordpress/
